## Cache oblivious matrix multiplication

In [1]:
import numpy as np 
# we'll try to implement the recursive matrix multiplication

In [165]:
def fib(n):
    if n==0 or n==1:
        return n
    else:
        return fib(n-1)+fib(n-2)
    
print(fib(7))

13


In [85]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [86]:
C = np.matmul(A, B)
print(C, A[0:2, :])

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]] [[1 2 3]
 [4 5 6]]


In [87]:
[m, n] = np.shape(A)
[n, p] = np.shape(B)
C = np.zeros((m, p))
print(C, m, n, p)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] 3 3 3


In [108]:
def mat_mul(A, B, C): # dividing the `m'
    m, n = np.shape(A)
    _, p = np.shape(B)
    if m==1: # do the vector multiplication 
        print(A, B, C)
        for i in range(p):
            for j in range(n):
                C[0][i] += A[0][j]*B[j][i]
        return
    else:
        mat_mul(A[0:int(m/2), :], B, C[0:int(m/2), :])
        mat_mul(A[int(m/2):, :], B, C[int(m/2):, :])

In [109]:
mat_mul(A, B, C)

[[1 2 3]] [[1 2 3]
 [4 5 6]
 [7 8 9]] [[ 30.  36.  42.]]
[[4 5 6]] [[1 2 3]
 [4 5 6]
 [7 8 9]] [[ 66.  81.  96.]]
[[7 8 9]] [[1 2 3]
 [4 5 6]
 [7 8 9]] [[ 102.  126.  150.]]


In [110]:
print(C)
C = np.zeros((m, p))

[[  60.   72.   84.]
 [ 132.  162.  192.]
 [ 204.  252.  300.]]


In [111]:
# Dividing the N
def mat_mul2(A, B):
    m, n = np.shape(A)
    _, p = np.shape(B)
    print(m, n, p)
    if n == 1:
        print(A, B)
        C = np.zeros((3, 3))
        print(C)
#        C = np.matmul(A, B)
        for i in range(m):
            for j in range(p):
                C[i][j] = A[i][0]*B[0][j]
        return C
    else:
        return mat_mul2(A[:, 0:int(n/2)], B[0:int(n/2), :])+mat_mul2(A[:, int(n/2):], B[int(n/2):, :])

In [112]:
C = mat_mul2(A, B)

3 3 3
3 1 3
[[1]
 [4]
 [7]] [[1 2 3]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
3 2 3
3 1 3
[[2]
 [5]
 [8]] [[4 5 6]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
3 1 3
[[3]
 [6]
 [9]] [[7 8 9]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [113]:
print(C)

[[  30.   36.   42.]
 [  66.   81.   96.]
 [ 102.  126.  150.]]


## Complete recursive implementation of matrix multiplication

In [ ]:
    print('a')
    print(A)
    print('b')
    print(B)
    print('c')
    print(C)

In [221]:
# for square matrices
def recursive_mat_wrong(A, B, C):
    m, n = np.shape(A)
    _, p = np.shape(B)
    print(m, n, p)
    if m==1 and n==1 and p==1:
        print(A, B[0], C[0][0])
#        C[0][0] += A[0][0]*B[0][0]
#        return C[0][0]
        return A[0][0]*B[0][0]
    else:
        
        C[0:int(m/2), 0:int(p/2)] = (recursive_mat(A[0:int(m/2), 0:int(n/2)], B[0:int(n/2), 0:int(p/2)], C[0:int(m/2), 0:int(p/2)]) 
                                 + recursive_mat(A[0:int(m/2), int(n/2):], B[int(n/2):, 0:int(p/2)], C[0:int(m/2), 0:int(p/2)] ))
        
        C[0:int(m/2), int(p/2):] = (recursive_mat(A[0:int(m/2), 0:int(n/2)], B[0:int(n/2), int(p/2):], C[0:int(m/2), int(p/2):]) 
                                 + recursive_mat(A[0:int(m/2), int(n/2):], B[int(n/2):, int(p/2):], C[0:int(m/2), int(p/2):] ))
        
        C[int(m/2):, 0:int(p/2)] = (recursive_mat(A[int(m/2):, 0:int(n/2)], B[0:int(n/2), 0:int(p/2)], C[int(m/2):, 0:int(p/2)]) 
                                 + recursive_mat(A[int(m/2):, int(n/2):], B[int(n/2):, 0:int(p/2)], C[int(m/2):, 0:int(p/2)] ))
        
        C[int(m/2):, int(p/2):] = (recursive_mat(A[int(m/2):, 0:int(n/2)], B[0:int(n/2), int(p/2):], C[int(m/2):, int(p/2):]) 
                                 + recursive_mat(A[int(m/2):, int(n/2):], B[int(n/2):, int(p/2):], C[int(m/2):, int(p/2):] ))
        return C

In [232]:
# for power of 2 square matrices
def recursive_mat(A, B):
    m, n = np.shape(A)
    _, p = np.shape(B)
    if m==1 and n==1 and p==1:
#        print(A, B[0])
#        C[0][0] += A[0][0]*B[0][0]
#        return C[0][0]
        return A[0][0]*B[0][0]
    else:
        C = np.zeros((m, p))
        C[0:int(m/2), 0:int(p/2)] = (recursive_mat(A[0:int(m/2), 0:int(n/2)], B[0:int(n/2), 0:int(p/2)],) 
                                 + recursive_mat(A[0:int(m/2), int(n/2):], B[int(n/2):, 0:int(p/2)]))
        
        C[0:int(m/2), int(p/2):] = (recursive_mat(A[0:int(m/2), 0:int(n/2)], B[0:int(n/2), int(p/2):]) 
                                 + recursive_mat(A[0:int(m/2), int(n/2):], B[int(n/2):, int(p/2):] ))
        
        C[int(m/2):, 0:int(p/2)] = (recursive_mat(A[int(m/2):, 0:int(n/2)], B[0:int(n/2), 0:int(p/2)]) 
                                 + recursive_mat(A[int(m/2):, int(n/2):], B[int(n/2):, 0:int(p/2)]))
        
        C[int(m/2):, int(p/2):] = (recursive_mat(A[int(m/2):, 0:int(n/2)], B[0:int(n/2), int(p/2):]) 
                                 + recursive_mat(A[int(m/2):, int(n/2):], B[int(n/2):, int(p/2):] ))
        return C

In [233]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
X = 0
A = np.array([[1,2,3,0], [4,5,6,0], [7,8,9,0], [1,1,1,1]])
B = np.array([[1,2,3,0], [4,5,6,0], [7,8,9,0], [1,1,1,1]])

m, n = np.shape(A)
#C = np.zeros((m, n))
C = recursive_mat(A, B)
print(C)
print('actual')
print(np.matmul(A, B))

[[  30.   36.   42.    0.]
 [  66.   81.   96.    0.]
 [ 102.  126.  150.    0.]
 [  13.   16.   19.    1.]]
actual
[[ 30  36  42   0]
 [ 66  81  96   0]
 [102 126 150   0]
 [ 13  16  19   1]]


In [234]:
max(2, 3)

3

In [167]:
A+A

array([[ 2,  4,  6,  0],
       [ 8, 10, 12,  0],
       [14, 16, 18,  0],
       [ 2,  2,  2,  2]])

# Cache oblivious for rectangular matrices

In [235]:
def rect_mul(A, B):
    m, n = np.shape(A)
    n1, p = np.shape(B)
    if(n1!=n):
        print('abort!')
        return -1
    if m==1 and n==1 and p==1:
        return A[0][0]*B[0][0]
    else:
        #3 cases
        C = np.zeros((m, p)) # temporary matrix
        if m >= max(n, p):
            C[0:m/2, :] = rect_mul(A[0:m/2, :], B) 
            C[m/2:, :] = rect_mul(A[m/2:, :], B)
        elif n>=max(m, p):
            C = rect_mul(A[:, 0:n/2], B[0:n/2, :]) + rect_mul(A[:, n/2:], B[n/2:, :])
        elif p>=max(m, n):
            C[:, 0:p/2] = rect_mul(A, B[:, 0:p/2])
            C[:, p/2:] = rect_mul(A, B[:, p/2:])
        return C

In [237]:
A = np.array([[1,2,3], [4,5,6], [7,8,9], [7,8,9]])
B = np.array([[1,2,3], [4,5,6], [7,8,9]])
C = rect_mul(A, B)
print(C)
print('actual')
print(np.matmul(A, B))

[[  30.   36.   42.]
 [  66.   81.   96.]
 [ 102.  126.  150.]
 [ 102.  126.  150.]]
actual
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]
 [102 126 150]]


C:\Users\Harsh\Anaconda3\lib\site-packages\ipykernel\__main__.py:13: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\Harsh\Anaconda3\lib\site-packages\ipykernel\__main__.py:16: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\Harsh\Anaconda3\lib\site-packages\ipykernel\__main__.py:18: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\Harsh\Anaconda3\lib\site-packages\ipykernel\__main__.py:14: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\Harsh\Anaconda3\lib\site-packages\ipykernel\__main__.py:19: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
